server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dubbotest?serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  dubbo: # dubbo配置
    application:
      name: consumer
    registry:
      address: zookeeper://127.0.0.1:2181  # dubbo注册地址
    protocal:
      name: dubbo
      port: 20880
